import assert from "node:assert/strict";
import type { PathCase } from "./harness";

const emails = (r: any) => r.outbox.filter((o: any) => o.channel === "email" && o.status === "held").length;

export const cases: PathCase[] = [
  { name: "ready to book → recovered checkout → verified booking stops follow-up", scenario: "ready_to_book", steps: ["ready", "complete"], expect: { status: "completed", outcome: "success", events: ["Original quote A$190/night is stale", "Live rate A$205/night", "Unresolved question answered", "Checkout session", "verified in booking engine", "follow-up stopped"], records: { booking: "Confirmed", checkout: "Completed", enquiry: "Recovered" }, check: (r) => { assert.equal(emails(r), 1); assert.match(r.records.find((x: any) => x.id === "booking")!.fields.find((f: any) => f.label === "Rate")!.value, /A\$205/); } } },
  { name: "offer never reuses the stale enquiry price", scenario: "ready_to_book", steps: [], expect: { status: "waiting_customer", check: (r) => { const last = r.messages.filter((m: any) => m.from === "assistant").at(-1)!.text; assert.ok(last.includes("A$205") && !last.includes("A$190")); } } },
  { name: "expired rate requires refresh before checkout", scenario: "ready_to_book", steps: ["ready", "wait", "complete", "accept_refreshed", "complete"], expect: { status: "completed", outcome: "success", events: ["expired — rate must be refreshed", "Rate refreshed: A$215/night"], check: (r) => assert.match(r.records.find((x: any) => x.id === "booking")!.fields.find((f: any) => f.label === "Rate")!.value, /A\$215/) } },
  { name: "already booked suppresses contact", scenario: "already_booked", steps: [], expect: { status: "stopped", events: ["Already booked — contact suppressed"], records: { enquiry: "already booked" }, check: (r) => assert.equal(emails(r), 0) } },
  { name: "sold-out room is never offered as available", scenario: "sold_out", steps: [], expect: { status: "waiting_customer", events: ["sold out", "offering alternatives"], check: (r) => { assert.ok(!r.actions.some((a: any) => a.id === "ready")); assert.ok(r.actions.some((a: any) => a.id === "alt_room")); assert.equal(r.records.find((x: any) => x.id === "availability")!.status, "Original room sold out"); } } },
  { name: "sold out: alternative booked at live rate", scenario: "sold_out", steps: ["alt_room", "complete"], expect: { status: "completed", outcome: "success", events: ["Alternative chosen: Garden Twin"], records: { booking: "Confirmed" }, check: (r) => assert.match(r.records.find((x: any) => x.id === "booking")!.fields.find((f: any) => f.label === "Stay")!.value, /Garden Twin/) } },
  { name: "opt-out ends the sequence", scenario: "no_reply", steps: ["wait", "opt_out"], expect: { status: "stopped", outcome: "stopped", events: ["Opt-out recorded"], records: { enquiry: "opted out" }, check: (r) => assert.equal(emails(r), 2) } },
  { name: "no reply closes at contact limit", scenario: "no_reply", steps: ["wait", "wait", "wait"], expect: { status: "stopped", outcome: "exception", events: ["Limited retry", "Contact limit reached"], records: { enquiry: "no reply" }, check: (r) => assert.equal(emails(r), 3) } },
  { name: "booking via another channel stops follow-up", scenario: "no_reply", steps: ["wait", "booked_web"], expect: { status: "completed", events: ["Confirmed booking found", "follow-up stopped"], check: (r) => assert.equal(emails(r), 2) } },
  { name: "free text: unclear twice hands to owner", scenario: "ready_to_book", steps: ["free:what about the dog", "free:hmm the dog"], expect: { status: "stopped", events: ["Reply not understood", "human takeover"] } },
  { name: "free text: yes please returns to checkout", scenario: "ready_to_book", steps: ["free:yes please, book it"], expect: { status: "waiting_customer", events: ["Checkout session"] } },
];
