import assert from "node:assert/strict";
import type { PathCase } from "./harness";

export const cases: PathCase[] = [
  { name: "lapsed regular → interested → booked, sequence ends", scenario: "lapsed_regular", steps: ["interested", "book_first"], expect: { status: "completed", outcome: "success", events: ["Unusual lapse", "Approved offer", "Return visit booked", "booking ends the sequence"], records: { booking: "Booked", campaign: "Won back", eligibility: "Eligible" }, check: (r) => { assert.equal(r.outbox.filter((o) => o.channel === "sms").length, 1); assert.equal(r.actions.length, 0); } } },
  { name: "lapse calculated against own interval", scenario: "lapsed_regular", steps: [], expect: { status: "waiting_customer", check: (r) => assert.match(r.records.find((x) => x.id === "eligibility")!.fields.find((f) => f.label === "Lapse")!.value, /2\.8× usual interval/) } },
  { name: "complaint suppresses promotion and creates follow-up task", scenario: "open_complaint", steps: [], expect: { status: "waiting_staff", events: ["Open complaint — promotion suppressed", "Complaint follow-up task created"], noEvents: ["Invitation queued"], records: { eligibility: "open complaint", task: "Assigned" }, check: (r) => { assert.equal(r.outbox.filter((o) => o.channel === "sms" && o.status === "held").length, 0); assert.equal(r.outbox.filter((o) => o.channel === "task").length, 1); } } },
  { name: "complaint resolved by staff via service recovery", scenario: "open_complaint", steps: ["staff_resolved"], expect: { status: "completed", outcome: "exception", events: ["Service recovery booked"], records: { task: "Completed" } } },
  { name: "negative reply creates a staff task and stops promotion", scenario: "lapsed_regular", steps: ["unhappy"], expect: { status: "waiting_staff", events: ["Reply classified: unhappy", "Staff task created for negative reply"], records: { task: "Assigned", campaign: "Paused" } } },
  { name: "opt-out reply blocks later campaigns", scenario: "lapsed_regular", steps: ["opt_out"], expect: { status: "stopped", outcome: "stopped", events: ["Opt-out recorded", "Later campaign blocked"], records: { campaign: "opted out" } } },
  { name: "opted-out customer is never contacted", scenario: "opted_out", steps: [], expect: { status: "stopped", events: ["Opted out — excluded"], check: (r) => assert.equal(r.outbox.filter((o) => o.status === "held").length, 0) } },
  { name: "frequency cap defers contact", scenario: "frequency_cap", steps: [], expect: { status: "stopped", outcome: "exception", events: ["Frequency cap reached"], records: { eligibility: "frequency cap" }, check: (r) => assert.equal(r.outbox.filter((o) => o.status === "held").length, 0) } },
  { name: "not lapsed → no contact", scenario: "not_lapsed", steps: [], expect: { status: "stopped", events: ["Not lapsed"], records: { eligibility: "not lapsed" } } },
  { name: "no reply stops at contact limit", scenario: "lapsed_regular", steps: ["wait", "wait"], expect: { status: "stopped", events: ["Reminder queued", "contact limit"], check: (r) => assert.equal(r.outbox.filter((o) => o.channel === "sms").length, 2) } },
  { name: "free text: unclear asks, then understood yes", scenario: "lapsed_regular", steps: ["free:what time is it", "free:yes please book me in"], expect: { status: "waiting_customer", events: ["Reply not understood", "Reply classified: interested"] } },
  { name: "not interested → later eligibility check", scenario: "lapsed_regular", steps: ["not_interested"], expect: { status: "stopped", events: ["Not ready"], records: { campaign: "not ready" } } },
  { name: "defect: 'No worries, yes please book me in' is interested", scenario: "lapsed_regular", steps: ["free:No worries, yes please book me in"], expect: { status: "waiting_customer", events: ["Reply classified: interested"], noEvents: ["Not ready", "unhappy"] } },
  { name: "defect: 'not too bad' is not a complaint", scenario: "lapsed_regular", steps: ["free:Not too bad thanks, sure"], expect: { status: "waiting_customer", noEvents: ["unhappy", "Staff task"], check: (r) => assert.equal(r.outbox.filter((o) => o.channel === "task").length, 0) } },
  { name: "defect: phone numbers use the fictional 0491 570 range", scenario: "lapsed_regular", steps: [], expect: { check: (r) => { for (const o of r.outbox.filter((x) => x.channel === "sms")) assert.match(o.to, /^0491 570 \d{3}$/); } } },
];
