import assert from "node:assert/strict";
import type { PathCase } from "./harness";

export const cases: PathCase[] = [
  { name: "family books after payment success event", scenario: "family_stay", steps: ["choose_courtyard", "pay_ok"], expect: { status: "completed", outcome: "success", events: ["Live recheck", "Payment event", "succeeded", "Booking", "confirmed"], records: { booking: "Confirmed", checkout: "Completed" }, check: (r) => { assert.equal(r.outbox.filter((o) => o.channel === "calendar").length, 1); assert.ok(r.events.some((e) => e.status === "blocked" && e.node === "verify")); } } },
  { name: "party size excludes unsuitable rooms", scenario: "family_stay", steps: [], expect: { status: "waiting_customer", events: ["Loft Twin excluded", "sleeps 2, party is 3"], check: (r) => { const ids = r.actions.map((a) => a.id); assert.ok(!ids.includes("choose_loft") && !ids.includes("choose_garden")); assert.ok(ids.includes("choose_family")); } } },
  { name: "checkout is reservation intent, not a booking", scenario: "family_stay", steps: ["choose_family"], expect: { status: "waiting_customer", records: { checkout: "Reservation intent" }, check: (r) => { assert.ok(!r.events.some((e) => e.status === "confirmed")); assert.ok(!r.records.some((x) => x.id === "booking")); assert.match(r.records.find((x) => x.id === "checkout")!.fields.find((f) => f.label === "Card details")!.value, /Not collected/); } } },
  { name: "sold-out dates suggest alternatives", scenario: "sold_out", steps: ["date_0", "choose_family", "pay_ok"], expect: { status: "completed", outcome: "success", events: ["suggesting alternatives", "Dates changed to Fri 14 Nov"] } },
  { name: "sold-out: decline alternatives closes", scenario: "sold_out", steps: ["no_thanks"], expect: { status: "stopped", outcome: "exception", records: { match: "Closed" } } },
  { name: "failed payment never shows a confirmed stay", scenario: "payment_failed", steps: ["choose_garden", "pay_fail"], expect: { status: "waiting_customer", records: { booking: "Not confirmed" }, check: (r) => { assert.equal(r.outbox.filter((o) => o.channel === "calendar").length, 0); assert.ok(!r.events.some((e) => e.status === "confirmed")); } } },
  { name: "failed payment twice closes checkout", scenario: "payment_failed", steps: ["choose_garden", "pay_fail", "pay_fail"], expect: { status: "failed", outcome: "failed", records: { booking: "Not confirmed" }, noEvents: ["Booking BK"] } },
  { name: "retry safely after failure then success", scenario: "payment_failed", steps: ["choose_garden", "pay_fail", "pay_ok"], expect: { status: "completed", outcome: "success", records: { booking: "Confirmed" } } },
  { name: "unsupported accessibility question → staff, no promise", scenario: "accessibility", steps: [], expect: { status: "waiting_customer", events: ["No approved fact", "handed to staff"], records: { handoff: "front desk" }, check: (r) => assert.equal(r.outbox.filter((o) => o.channel === "task").length, 1) } },
  { name: "free-text wheelchair question hands off; approved fact answered", scenario: "family_stay", steps: ["free:Do you have wheelchair access?", "free:What time is check-in?"], expect: { status: "waiting_customer", events: ["Unknown property detail", "Answered from approved property facts"] } },
  { name: "live inventory recheck catches room sold elsewhere", scenario: "family_stay", steps: ["choose_family", "taken", "pay_ok"], expect: { status: "waiting_customer", events: ["no longer available"], records: { checkout: "Cancelled" }, check: (r) => { assert.equal(r.outbox.filter((o) => o.channel === "payment").length, 0); assert.ok(!r.actions.some((a) => a.id === "choose_family")); } } },
  { name: "party too large → staff, nothing offered", scenario: "large_party", steps: [], expect: { status: "stopped", outcome: "exception", events: ["No single room"], check: (r) => assert.ok(!r.records.some((x) => x.id === "checkout")) } },
];
