import assert from "node:assert/strict";
import type { PathCase } from "./harness";

const rec = (r: any, id: string) => r.records.find((x: any) => x.id === id);

export const cases: PathCase[] = [
  { name: "birthday cake: missing details asked, owner approves, deposit confirms order", scenario: "cake_complete", steps: ["answer", "owner_approve", "pay_deposit", "ticket_ack"], expect: { status: "completed", outcome: "success", events: ["Missing details: date, serving count", "Order brief complete", "Owner approved quote", "Deposit event", "Order ORD-"], records: { brief: "Complete", order: "Confirmed", request: "Confirmed order" }, check: (r) => assert.equal(r.outbox.filter((o: any) => o.channel === "task").length, 1) } },
  { name: "unpaid approved quote stays distinct from an order", scenario: "cake_complete", steps: ["answer", "owner_approve"], expect: { status: "waiting_customer", records: { request: "deposit unpaid (not an order)", quote: "Approved" }, check: (r) => assert.ok(!rec(r, "order")) } },
  { name: "unpaid quote expires without an order", scenario: "cake_complete", steps: ["answer", "owner_approve", "expire"], expect: { status: "stopped", outcome: "exception", records: { request: "Unpaid" }, check: (r) => assert.ok(!rec(r, "order")) } },
  { name: "missing date blocks checkout", scenario: "missing_date", steps: ["answer"], expect: { status: "waiting_customer", events: ["Checkout blocked — no date"], noEvents: ["Slot provisionally held", "Quote v1"], records: { brief: "Incomplete — missing date", request: "checkout blocked" }, check: (r) => { assert.ok(!rec(r, "quote")); assert.ok(!r.actions.some((a: any) => a.id === "pay_deposit")); } } },
  { name: "adding the date unblocks the brief", scenario: "missing_date", steps: ["answer", "give_date"], expect: { status: "waiting_staff", events: ["Date added", "Order brief complete"], records: { brief: "Complete", quote: "Draft" } } },
  { name: "full production day offers alternatives", scenario: "capacity_full", steps: [], expect: { status: "waiting_customer", events: ["fully booked", "Capacity full — alternative dates offered"], check: (r) => { assert.deepEqual(r.actions.filter((a: any) => a.id.startsWith("alt")).map((a: any) => a.label), ["Choose Fri 10 Oct", "Choose Sun 12 Oct"]); assert.ok(!rec(r, "quote")); } } },
  { name: "alternative date accepted and quoted", scenario: "capacity_full", steps: ["alt2"], expect: { status: "waiting_staff", events: ["Customer chose alternative date Sun 12 Oct", "Sun 12 Oct: 1 slot free"], records: { quote: "Draft" } } },
  { name: "customer who cannot move is not overbooked", scenario: "capacity_full", steps: ["keep_date"], expect: { status: "stopped", records: { request: "date unavailable" } } },
  { name: "dietary request flagged without safety guarantee; custom design needs owner", scenario: "dietary_custom", steps: [], expect: { status: "waiting_staff", events: ["Dietary request flagged for owner", "Custom design needs owner review"], check: (r) => { const said = r.messages.filter((m: any) => m.from === "assistant").map((m: any) => m.text).join(" "); assert.ok(said.includes("can’t promise")); assert.ok(!/\b(safe to eat|guaranteed? (nut|allergen)[- ]free)\b/i.test(said)); assert.ok(rec(r, "quote").fields.some((f: any) => f.value.startsWith("Not priced"))); } } },
  { name: "owner revision loop then approval with design fee", scenario: "dietary_custom", steps: ["owner_revise", "clarify_reply", "owner_approve", "pay_deposit", "ticket_ack"], expect: { outcome: "success", events: ["Brief needs revision", "Owner approved custom design fee", "Owner reviewed dietary request"], check: (r) => { assert.ok(rec(r, "quote").ref.endsWith("v2")); assert.ok(rec(r, "order").fields.some((f: any) => f.label === "Dietary")); } } },
  { name: "only catalogue prices are calculated", scenario: "flowers", steps: ["owner_approve"], expect: { records: { quote: "Approved" }, check: (r) => { const q = rec(r, "quote"); assert.equal(q.fields.find((f: any) => f.label === "Total").value, "A$125"); assert.equal(q.fields.find((f: any) => f.label === "Deposit (50%)").value, "A$63"); } } },
  { name: "duplicate deposit event creates one order", scenario: "flowers", steps: ["owner_approve", "pay_deposit", "replay", "replay"], expect: { status: "waiting_staff", events: ["received again", "Duplicate deposit event ignored", "Duplicate production ticket ignored"], check: (r) => { assert.equal(r.outbox.filter((o: any) => o.channel === "task").length, 1); assert.equal(r.outbox.filter((o: any) => o.channel === "payment").length, 1); assert.equal(r.records.filter((x: any) => x.id === "order").length, 1); } } },
  { name: "free text fills the brief with keyword rules", scenario: "cake_complete", steps: ["free:It's for Sunday, 20 people, I'll collect at 10am"], expect: { status: "waiting_staff", events: ["Reply parsed", "Order brief complete"], check: (r) => assert.equal(rec(r, "brief").fields.find((f: any) => f.label === "Date").value, "Sun 12 Oct") } },
  { name: "unclear free text asks again, never pretends", scenario: "cake_complete", steps: ["free:yes please"], expect: { status: "waiting_customer", events: ["Reply not understood"], records: { brief: "Incomplete" } } },
  { name: "repeated unclear replies hand off to owner", scenario: "missing_date", steps: ["free:hmm", "free:yes please", "free:2000"], expect: { status: "stopped", events: ["Handed to owner"], records: { request: "Incomplete enquiry" } } },
];
