/**
 * Builds the source-specific "Lead Qualification Starter Pack" as Markdown
 * and triggers a client-side download. No backend, no dependencies.
 */

import {
  SCORE_COMPONENTS,
  SCORE_BANDS,
  BASE_POINTS,
  buildWorkflow,
  buildGuide,
  buildChecklist,
  channelLabel,
  type Source,
} from "./leadQualifierData";

export function buildMarkdown(s: Source): string {
  const workflow = buildWorkflow(s);
  const guide = buildGuide(s);
  const checklist = buildChecklist(s);
  const L: string[] = [];

  L.push(`# Lead Qualification Starter Pack`);
  L.push(`## ${s.title}`);
  L.push("");
  L.push(`> ${s.description}`);
  L.push("");
  L.push(
    `Source weight: **${s.weight > 0 ? "+" : ""}${s.weight}** · Routing posture: **${s.posture}**`
  );
  L.push("");
  L.push(`*Generated by HackrLife AgentLab — Lead Qualification Agent.*`);
  L.push("");
  L.push("---");
  L.push("");

  // 1. Prompt
  L.push(`## 1. Agent Prompt`);
  L.push("");
  L.push("```text");
  L.push(s.prompt);
  L.push("```");
  L.push("");

  // 2. Scoring
  L.push(`## 2. Lead-to-Sales Score (${BASE_POINTS}-point base)`);
  L.push("");
  L.push(`| Component | Points | What it measures |`);
  L.push(`| --- | ---: | --- |`);
  for (const c of SCORE_COMPONENTS) {
    L.push(`| ${c.label} | ${c.points} | ${c.description} |`);
  }
  L.push(`| **Base total** | **${BASE_POINTS}** | |`);
  L.push("");
  L.push(
    `**Final score = base score ${s.weight >= 0 ? "+" : "−"} ${Math.abs(
      s.weight
    )} (source weight), capped 0–100.**`
  );
  L.push("");

  // 3. Bands
  L.push(`## 3. Scoring Bands`);
  L.push("");
  L.push(`| Score | Band |`);
  L.push(`| --- | --- |`);
  for (const b of SCORE_BANDS) {
    L.push(`| ${b.range} | ${b.label} |`);
  }
  L.push("");

  // 4. Routing & actions
  L.push(`## 4. Routing & Actions (${s.title})`);
  L.push("");
  L.push(`| Band | Action |`);
  L.push(`| --- | --- |`);
  for (const r of s.routing) {
    L.push(`| ${r.band} | ${r.action} |`);
  }
  L.push("");

  // 5. Automation workflow
  L.push(`## 5. Automation Workflow (human in the loop)`);
  L.push("");
  workflow.forEach((step, i) => {
    L.push(`${i + 1}. **${step.title}**`);
  });
  L.push("");

  // 6. Cadence (with full copy)
  L.push(`## 6. Outreach Cadence — ${s.cadenceIntensity}`);
  L.push("");
  L.push(
    `${s.cadence.length} steps. Tool-neutral; imports to SalesLoft, Outreach, or HubSpot.`
  );
  L.push("");
  s.cadence.forEach((step, i) => {
    L.push(`### Step ${i + 1} · Day ${step.day} · ${channelLabel[step.channel]}`);
    L.push(`*${step.intent}*`);
    L.push("");
    L.push(step.copy);
    L.push("");
  });

  // 7. Implementation guide
  L.push(`## 7. Implementation Guide`);
  L.push("");
  for (const part of guide) {
    L.push(`### ${part.n}. ${part.title}`);
    for (const b of part.bullets) L.push(`- ${b}`);
    L.push("");
  }

  // 8. Deployment checklist
  L.push(`## 8. Deployment Checklist`);
  L.push("");
  for (const d of checklist) {
    L.push(`- [ ] **Day ${d.day} — ${d.title}:** ${d.task}`);
  }
  L.push("");

  // CTA
  L.push("---");
  L.push("");
  L.push(`## Ready to deploy this for ${s.title}?`);
  L.push("");
  L.push(
    "Book a consult and we'll calibrate the scoring, routing, and cadence to your offer and wire the automation into your stack — with a human approval step you control."
  );
  L.push("");
  L.push(`**HackrLife AgentLab** · agents.hackrlife.com`);
  L.push("");

  return L.join("\n");
}

export function downloadMarkdown(s: Source): void {
  const md = buildMarkdown(s);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `lead-qualification-agent-${s.slug}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
